IroncladDecoratorService:
  Db:
    LogsConnString:
      settings-key: IroncladDecoratorService-LogsConnString
      types:
        - AzureTableStorage
    ClientPersonalInfoConnString:
      settings-key: IroncladDecoratorService-ClientPersonalInfoConnString
    RedisConnString:
      settings-key: IroncladDecoratorService-RedisConnString
    DataProtectionSettings:
      BlobStorageConnString:
        settings-key: IroncladDecoratorService-DataProtectionSettings-BlobStorageConnString
      ContainerName: 
        settings-key: IroncladDecoratorService-DataProtectionSettings-ContainerName
      AppName: 
        settings-key: IroncladDecoratorService-DataProtectionSettings-AppName
      RelativePath: 
        settings-key: IroncladDecoratorService-DataProtectionSettings-RelativePath
  LifetimeSettings:
    settings-key: IroncladDecoratorService-LifetimeSettings
    types:
      - Json
  IroncladSettings:
    IroncladIdp:
      settings-key: IroncladDecoratorService-IroncladSettings-IroncladIdp
      types:
        - Json
    AuthClient:
      settings-key: IroncladDecoratorService-IroncladSettings-AuthClient
      types:
        - Json
    IntrospectionClient:
      settings-key: IroncladDecoratorService-IroncladSettings-IntrospectionClient
      types:
        - Json
    AndroidClient:
      settings-key: IroncladDecoratorService-IroncladSettings-AndroidClient
      types:
        - Json
    IosClient:
      settings-key: IroncladDecoratorService-IroncladSettings-IosClient
      types:
        - Json
SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
        - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName
ClientAccountClient:
  ServiceUrl:
    settings-key: ClientAccountServiceUrl
SessionServiceClient:
  ServiceUrl:
    settings-key: SessionServiceUrl
MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl
