IroncladDecoratorService:
  Db:
    LogsConnString:
      settings-key: IroncladDecoratorService-LogsConnString
      types:
        - AzureTableStorage
  LifetimeSettings:
    settings-key: IroncladDecoratorService-LifetimeSettings
    types:
      - Json
  IroncladSettings:
    IroncladIdp:
      settings-key: IroncladDecoratorService-IroncladSettings-IroncladIdp
      types:
        - Json
    AuthClient:
      settings-key: IroncladDecoratorService-IroncladSettings-AuthClient
      types:
        - Json
    IntrospectionClient:
      settings-key: IroncladDecoratorService-IroncladSettings-IntrospectionClient
      types:
        - Json
SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
        - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName
ClientAccountClient:
  ServiceUrl:
    settings-key: ClientAccountServiceUrl
SessionServiceClient:
  ServiceUrl:
    settings-key: SessionServiceUrl
MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl
